version: "3.7"

services:

  iam-migrations:
    image: leblancisc/covid-19-challenge:iam.IAM-stable
    command: kong migrations up
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: IAM
      KONG_PG_HOST: RDSDB
      KONG_PG_PASSWORD: intersystems
      KONG_PG_USER: intersystems
      KONG_CASSANDRA_CONTACT_POINTS: RDSDB
      ISC_IRIS_URL: "http://IAM:sys@172.31.0.10:52773/api/iam/license"
    restart: on-failure
  iam:
    image: leblancisc/covid-19-challenge:iam.IAM-stable
    hostname: iam
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ANONYMOUS_REPORTS: "off"
      KONG_CASSANDRA_CONTACT_POINTS: RDSDB
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: IAM
      KONG_PG_HOST: RDSDB
      KONG_PG_PASSWORD: intersystems
      KONG_PG_USER: intersystems
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PORTAL: "on"
      KONG_PORTAL_GUI_PROTOCOL: http
      KONG_PORTAL_GUI_HOST: "ELBDNS:8003"
      KONG_API_PORTAL_URL: "http://ELBDNS:8444"
      KONG_ADMIN_GUI_AUTH: basic-auth
      KONG_ADMIN_GUI_AUTH_CONF: { "hide_credentials": true }
      KONG_PASSWORD: PASSWORD
      ISC_IRIS_URL: "http://IAM:sys@172.31.0.10:52773/api/iam/license"
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
      - target: 8001
        published: 8001
        protocol: tcp
      - target: 8002
        published: 8002
        protocol: tcp
      - target: 8003
        published: 8003
        protocol: tcp
      - target: 8004
        published: 8004
        protocol: tcp
      - target: 8443
        published: 8443
        protocol: tcp
      - target: 8444
        published: 8444
        protocol: tcp
      - target: 8445
        published: 8445
        protocol: tcp
    restart: on-failure

